# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "bump version code"
  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/

    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc 'Deploy a new internal version to the Google Play Store'
    lane :beta do
        bump_version_code
        gradle(task: 'clean')
        gradle(
            task: 'assemble',
            build_type: 'Release'
          )
          supply(
            track: 'internal',
            apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH].to_s
          )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  lane :increase_build_number_and_push_to_beta do |values|
      # Increment the build number (not the version number)
      bump_version_code

      push_to_git_remote(
          remote_branch: "beta-android", # optional, default is set to local_branch
          force: true,    # optional, default: false
      )
  end
end
